# -*- coding: utf-8 -*-
"""internproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wTyd3eWLd-i8wX3jIrE-Lz7V5HcWJ4g
"""

pip install --upgrade langchain langchain-core langchain-community langchain-openai

"""project done"""

# AI Ad Copy Generator - Latest LangChain 2025 Compatible Version

import os
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain_core.runnables import RunnableSequence

# ------------------------------------
# 1. SET YOUR OPENAI API KEY
# ------------------------------------
os.environ["OPENAI_API_KEY"] = " -----------"

# ------------------------------------
# 2. LOAD MODEL
# ------------------------------------
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.7,
    max_tokens=250
)

# ------------------------------------
# 3. PROMPT TEMPLATE
# ------------------------------------
template = """
You are an expert digital marketer.
Generate a high-converting ad copy.

Product: {product}
Tone: {tone}

Create:
1. Catchy headline
2. Short ad description
3. Strong call-to-action
"""

prompt = PromptTemplate(
    input_variables=["product", "tone"],
    template=template
)

# ------------------------------------
# 4. CREATE PIPELINE (RunnableSequence)
# ------------------------------------
chain = RunnableSequence(prompt | llm)

# ------------------------------------
# 5. USER INPUT
# ------------------------------------
product_name = input("Enter product name: ")
tone_style = input("Enter tone (funny, emotional, professional): ")

# ------------------------------------
# 6. RUN
# ------------------------------------
result = chain.invoke({
    "product": product_name,
    "tone": tone_style
})

print("\n===== GENERATED AD COPY =====\n")
print(result.content)